default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username:
  password:
  template: template0

development:
  <<: *default
  database: Mixup_development

test:
  <<: *default
  database: Mixup_test

production:
  <<: *default
  database: Mixup_production
  username: Mixup
  password: <%= ENV['MIXUP_DATABASE_PASSWORD'] %>
